# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gate
email: ajeygore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  gate is a new age SSO solution. Gate allows you to create hosts, groups
  and users and provides authentication and authorisation across different kind of SSO
  Gate also allows you to setup VPN Solution - such as OpenVPN

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ajeygore
github_username:  ajeygore

# Build settings
markdown: kramdown
